/* Generated by re2c 3.0 on Thu Jun  1 11:13:43 2023 */
#line 1 "implicit.re"
#include "yaml.h"

char *Ryaml_find_implicit_tag(const char *str, size_t len)
{
  /* This bit was taken from implicit.re, which is in the Syck library.
   *
   * Copyright (C) 2003 why the lucky stiff */

  const char *cursor, *marker;
  cursor = str;


#line 16 "<stdout>"
{
	char yych;
	yych = *cursor;
	switch (yych) {
		case 0x00: goto yy1;
		case '+': goto yy4;
		case '-': goto yy5;
		case '.': goto yy6;
		case '0': goto yy7;
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy8;
		case '<': goto yy9;
		case '=': goto yy10;
		case 'F': goto yy11;
		case 'N': goto yy12;
		case 'T': goto yy13;
		case 'f': goto yy14;
		case 'n': goto yy15;
		case 't': goto yy16;
		case '~': goto yy17;
		default: goto yy2;
	}
yy1:
	++cursor;
#line 55 "implicit.re"
	{   return "null"; }
#line 50 "<stdout>"
yy2:
	++cursor;
yy3:
#line 101 "implicit.re"
	{   return "str"; }
#line 56 "<stdout>"
yy4:
	yych = *(marker = ++cursor);
	switch (yych) {
		case '.': goto yy18;
		case '0': goto yy20;
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy21;
		default: goto yy3;
	}
yy5:
	yych = *(marker = ++cursor);
	switch (yych) {
		case '.': goto yy23;
		case '0': goto yy20;
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy21;
		default: goto yy3;
	}
yy6:
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy24;
		case ',': goto yy25;
		case '.': goto yy27;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy28;
		case 'E':
		case 'e': goto yy29;
		case 'I': goto yy30;
		case 'N': goto yy31;
		case 'i': goto yy32;
		case 'n': goto yy33;
		default: goto yy3;
	}
yy7:
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy34;
		case ',': goto yy35;
		case '.': goto yy28;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7': goto yy37;
		case '8':
		case '9': goto yy38;
		case ':': goto yy39;
		case 'x': goto yy40;
		default: goto yy3;
	}
yy8:
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy34;
		case ',': goto yy21;
		case '.': goto yy28;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy41;
		case ':': goto yy39;
		default: goto yy3;
	}
yy9:
	yych = *(marker = ++cursor);
	switch (yych) {
		case '<': goto yy42;
		default: goto yy3;
	}
yy10:
	yych = *++cursor;
	if (yych <= 0x00) goto yy43;
	goto yy3;
yy11:
	yych = *(marker = ++cursor);
	switch (yych) {
		case 'A': goto yy44;
		case 'a': goto yy45;
		default: goto yy3;
	}
yy12:
	yych = *(marker = ++cursor);
	switch (yych) {
		case 'U': goto yy46;
		case 'u': goto yy47;
		default: goto yy3;
	}
yy13:
	yych = *(marker = ++cursor);
	switch (yych) {
		case 'R': goto yy48;
		case 'r': goto yy49;
		default: goto yy3;
	}
yy14:
	yych = *(marker = ++cursor);
	switch (yych) {
		case 'a': goto yy45;
		default: goto yy3;
	}
yy15:
	yych = *(marker = ++cursor);
	switch (yych) {
		case 'u': goto yy47;
		default: goto yy3;
	}
yy16:
	yych = *(marker = ++cursor);
	switch (yych) {
		case 'r': goto yy49;
		default: goto yy3;
	}
yy17:
	yych = *++cursor;
	if (yych <= 0x00) goto yy1;
	goto yy3;
yy18:
	yych = *++cursor;
	switch (yych) {
		case '.': goto yy27;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy28;
		case 'E':
		case 'e': goto yy29;
		case 'I': goto yy30;
		case 'i': goto yy32;
		default: goto yy26;
	}
yy19:
	cursor = marker;
	goto yy3;
yy20:
	yych = *++cursor;
	switch (yych) {
		case 0x00: goto yy34;
		case 'x': goto yy40;
		default: goto yy36;
	}
yy21:
	yych = *++cursor;
yy22:
	switch (yych) {
		case 0x00: goto yy34;
		case ',':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy21;
		case '.': goto yy28;
		case ':': goto yy39;
		default: goto yy19;
	}
yy23:
	yych = *++cursor;
	switch (yych) {
		case '.': goto yy27;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy28;
		case 'E':
		case 'e': goto yy29;
		case 'I': goto yy52;
		case 'i': goto yy53;
		default: goto yy26;
	}
yy24:
	++cursor;
#line 73 "implicit.re"
	{   return "float#fix"; }
#line 279 "<stdout>"
yy25:
	yych = *++cursor;
yy26:
	switch (yych) {
		case 0x00: goto yy24;
		case ',':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy25;
		default: goto yy19;
	}
yy27:
	yych = *++cursor;
	switch (yych) {
		case '.':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy27;
		case 'E':
		case 'e': goto yy29;
		default: goto yy19;
	}
yy28:
	yych = *++cursor;
	switch (yych) {
		case 0x00: goto yy24;
		case ',': goto yy25;
		case '.': goto yy27;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy28;
		case 'E':
		case 'e': goto yy29;
		default: goto yy19;
	}
yy29:
	yych = *++cursor;
	switch (yych) {
		case '+':
		case '-': goto yy54;
		default: goto yy19;
	}
yy30:
	yych = *++cursor;
	switch (yych) {
		case 'N': goto yy55;
		case 'n': goto yy56;
		default: goto yy19;
	}
yy31:
	yych = *++cursor;
	switch (yych) {
		case 'A':
		case 'a': goto yy57;
		default: goto yy19;
	}
yy32:
	yych = *++cursor;
	switch (yych) {
		case 'n': goto yy56;
		default: goto yy19;
	}
yy33:
	yych = *++cursor;
	switch (yych) {
		case 'a': goto yy58;
		default: goto yy19;
	}
yy34:
	++cursor;
#line 71 "implicit.re"
	{   return "int"; }
#line 373 "<stdout>"
yy35:
	yych = *++cursor;
yy36:
	switch (yych) {
		case 0x00: goto yy59;
		case ',':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7': goto yy35;
		case '.': goto yy28;
		case '8':
		case '9': goto yy50;
		case ':': goto yy39;
		default: goto yy19;
	}
yy37:
	yych = *++cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7': goto yy60;
		case '8':
		case '9': goto yy61;
		default: goto yy36;
	}
yy38:
	yych = *++cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy61;
		default: goto yy51;
	}
yy39:
	yych = *++cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5': goto yy62;
		case '6':
		case '7':
		case '8':
		case '9': goto yy63;
		default: goto yy19;
	}
yy40:
	yych = *++cursor;
	if (yych <= 0x00) goto yy19;
	goto yy65;
yy41:
	yych = *++cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy66;
		default: goto yy22;
	}
yy42:
	yych = *++cursor;
	if (yych <= 0x00) goto yy67;
	goto yy19;
yy43:
	++cursor;
#line 97 "implicit.re"
	{   return "default"; }
#line 466 "<stdout>"
yy44:
	yych = *++cursor;
	switch (yych) {
		case 'L': goto yy68;
		default: goto yy19;
	}
yy45:
	yych = *++cursor;
	switch (yych) {
		case 'l': goto yy69;
		default: goto yy19;
	}
yy46:
	yych = *++cursor;
	switch (yych) {
		case 'L': goto yy70;
		default: goto yy19;
	}
yy47:
	yych = *++cursor;
	switch (yych) {
		case 'l': goto yy71;
		default: goto yy19;
	}
yy48:
	yych = *++cursor;
	switch (yych) {
		case 'U': goto yy72;
		default: goto yy19;
	}
yy49:
	yych = *++cursor;
	switch (yych) {
		case 'u': goto yy73;
		default: goto yy19;
	}
yy50:
	yych = *++cursor;
yy51:
	switch (yych) {
		case ',':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy50;
		case '.': goto yy28;
		case ':': goto yy39;
		default: goto yy19;
	}
yy52:
	yych = *++cursor;
	switch (yych) {
		case 'N': goto yy74;
		case 'n': goto yy75;
		default: goto yy19;
	}
yy53:
	yych = *++cursor;
	switch (yych) {
		case 'n': goto yy75;
		default: goto yy19;
	}
yy54:
	yych = *++cursor;
	if (yych <= 0x00) goto yy19;
	goto yy77;
yy55:
	yych = *++cursor;
	switch (yych) {
		case 'F': goto yy78;
		default: goto yy19;
	}
yy56:
	yych = *++cursor;
	switch (yych) {
		case 'f': goto yy78;
		default: goto yy19;
	}
yy57:
	yych = *++cursor;
	switch (yych) {
		case 'N': goto yy79;
		default: goto yy19;
	}
yy58:
	yych = *++cursor;
	switch (yych) {
		case 0x00: goto yy80;
		case '.': goto yy81;
		case 'n': goto yy79;
		default: goto yy19;
	}
yy59:
	++cursor;
#line 65 "implicit.re"
	{   return "int#oct"; }
#line 569 "<stdout>"
yy60:
	yych = *++cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7': goto yy82;
		case '8':
		case '9': goto yy83;
		default: goto yy36;
	}
yy61:
	yych = *++cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy83;
		default: goto yy51;
	}
yy62:
	yych = *++cursor;
	switch (yych) {
		case 0x00: goto yy84;
		case '.': goto yy85;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy63;
		case ':': goto yy39;
		default: goto yy19;
	}
yy63:
	yych = *++cursor;
	switch (yych) {
		case 0x00: goto yy84;
		case '.': goto yy85;
		case ':': goto yy39;
		default: goto yy19;
	}
yy64:
	yych = *++cursor;
yy65:
	switch (yych) {
		case 0x00: goto yy86;
		case ',':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy64;
		default: goto yy19;
	}
yy66:
	yych = *++cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy87;
		default: goto yy22;
	}
yy67:
	++cursor;
#line 99 "implicit.re"
	{   return "merge"; }
#line 675 "<stdout>"
yy68:
	yych = *++cursor;
	switch (yych) {
		case 'S': goto yy88;
		default: goto yy19;
	}
yy69:
	yych = *++cursor;
	switch (yych) {
		case 's': goto yy89;
		default: goto yy19;
	}
yy70:
	yych = *++cursor;
	switch (yych) {
		case 'L': goto yy90;
		default: goto yy19;
	}
yy71:
	yych = *++cursor;
	switch (yych) {
		case 'l': goto yy90;
		default: goto yy19;
	}
yy72:
	yych = *++cursor;
	switch (yych) {
		case 'E': goto yy91;
		default: goto yy19;
	}
yy73:
	yych = *++cursor;
	switch (yych) {
		case 'e': goto yy91;
		default: goto yy19;
	}
yy74:
	yych = *++cursor;
	switch (yych) {
		case 'F': goto yy92;
		default: goto yy19;
	}
yy75:
	yych = *++cursor;
	switch (yych) {
		case 'f': goto yy92;
		default: goto yy19;
	}
yy76:
	yych = *++cursor;
yy77:
	switch (yych) {
		case 0x00: goto yy93;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy76;
		default: goto yy19;
	}
yy78:
	yych = *++cursor;
	if (yych <= 0x00) goto yy94;
	goto yy19;
yy79:
	yych = *++cursor;
	if (yych <= 0x00) goto yy95;
	goto yy19;
yy80:
	++cursor;
#line 61 "implicit.re"
	{   return "bool#na"; }
#line 753 "<stdout>"
yy81:
	yych = *++cursor;
	switch (yych) {
		case 'c': goto yy96;
		case 'i': goto yy97;
		case 'r': goto yy98;
		default: goto yy19;
	}
yy82:
	yych = *++cursor;
	switch (yych) {
		case '-': goto yy99;
		default: goto yy36;
	}
yy83:
	yych = *++cursor;
	switch (yych) {
		case '-': goto yy99;
		default: goto yy51;
	}
yy84:
	++cursor;
#line 67 "implicit.re"
	{   return "int#base60"; }
#line 778 "<stdout>"
yy85:
	yych = *++cursor;
	switch (yych) {
		case 0x00: goto yy100;
		case ',':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy85;
		default: goto yy19;
	}
yy86:
	++cursor;
#line 63 "implicit.re"
	{   return "int#hex"; }
#line 800 "<stdout>"
yy87:
	yych = *++cursor;
	switch (yych) {
		case '-': goto yy99;
		default: goto yy22;
	}
yy88:
	yych = *++cursor;
	switch (yych) {
		case 'E': goto yy101;
		default: goto yy19;
	}
yy89:
	yych = *++cursor;
	switch (yych) {
		case 'e': goto yy101;
		default: goto yy19;
	}
yy90:
	yych = *++cursor;
	if (yych <= 0x00) goto yy1;
	goto yy19;
yy91:
	yych = *++cursor;
	if (yych <= 0x00) goto yy102;
	goto yy19;
yy92:
	yych = *++cursor;
	if (yych <= 0x00) goto yy103;
	goto yy19;
yy93:
	++cursor;
#line 75 "implicit.re"
	{   return "float#exp"; }
#line 835 "<stdout>"
yy94:
	++cursor;
#line 79 "implicit.re"
	{   return "float#inf"; }
#line 840 "<stdout>"
yy95:
	++cursor;
#line 83 "implicit.re"
	{   return "float#nan"; }
#line 845 "<stdout>"
yy96:
	yych = *++cursor;
	switch (yych) {
		case 'h': goto yy104;
		default: goto yy19;
	}
yy97:
	yych = *++cursor;
	switch (yych) {
		case 'n': goto yy105;
		default: goto yy19;
	}
yy98:
	yych = *++cursor;
	switch (yych) {
		case 'e': goto yy106;
		default: goto yy19;
	}
yy99:
	yych = *++cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy107;
		default: goto yy19;
	}
yy100:
	++cursor;
#line 77 "implicit.re"
	{   return "float#base60"; }
#line 883 "<stdout>"
yy101:
	yych = *++cursor;
	if (yych <= 0x00) goto yy108;
	goto yy19;
yy102:
	++cursor;
#line 57 "implicit.re"
	{   return "bool#yes"; }
#line 892 "<stdout>"
yy103:
	++cursor;
#line 81 "implicit.re"
	{   return "float#neginf"; }
#line 897 "<stdout>"
yy104:
	yych = *++cursor;
	switch (yych) {
		case 'a': goto yy109;
		default: goto yy19;
	}
yy105:
	yych = *++cursor;
	switch (yych) {
		case 't': goto yy110;
		default: goto yy19;
	}
yy106:
	yych = *++cursor;
	switch (yych) {
		case 'a': goto yy111;
		default: goto yy19;
	}
yy107:
	yych = *++cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy112;
		default: goto yy19;
	}
yy108:
	++cursor;
#line 59 "implicit.re"
	{   return "bool#no"; }
#line 935 "<stdout>"
yy109:
	yych = *++cursor;
	switch (yych) {
		case 'r': goto yy113;
		default: goto yy19;
	}
yy110:
	yych = *++cursor;
	switch (yych) {
		case 'e': goto yy114;
		default: goto yy19;
	}
yy111:
	yych = *++cursor;
	switch (yych) {
		case 'l': goto yy115;
		default: goto yy19;
	}
yy112:
	yych = *++cursor;
	switch (yych) {
		case '-': goto yy116;
		default: goto yy19;
	}
yy113:
	yych = *++cursor;
	switch (yych) {
		case 'a': goto yy117;
		default: goto yy19;
	}
yy114:
	yych = *++cursor;
	switch (yych) {
		case 'g': goto yy118;
		default: goto yy19;
	}
yy115:
	yych = *++cursor;
	if (yych <= 0x00) goto yy119;
	goto yy19;
yy116:
	yych = *++cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy120;
		default: goto yy19;
	}
yy117:
	yych = *++cursor;
	switch (yych) {
		case 'c': goto yy121;
		default: goto yy19;
	}
yy118:
	yych = *++cursor;
	switch (yych) {
		case 'e': goto yy122;
		default: goto yy19;
	}
yy119:
	++cursor;
#line 85 "implicit.re"
	{   return "float#na"; }
#line 1007 "<stdout>"
yy120:
	yych = *++cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy123;
		default: goto yy19;
	}
yy121:
	yych = *++cursor;
	switch (yych) {
		case 't': goto yy124;
		default: goto yy19;
	}
yy122:
	yych = *++cursor;
	switch (yych) {
		case 'r': goto yy125;
		default: goto yy19;
	}
yy123:
	yych = *++cursor;
	switch (yych) {
		case 0x00: goto yy126;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy19;
		case 'T':
		case 't': goto yy129;
		default: goto yy128;
	}
yy124:
	yych = *++cursor;
	switch (yych) {
		case 'e': goto yy130;
		default: goto yy19;
	}
yy125:
	yych = *++cursor;
	if (yych <= 0x00) goto yy131;
	goto yy19;
yy126:
	++cursor;
#line 87 "implicit.re"
	{   return "timestamp#ymd"; }
#line 1067 "<stdout>"
yy127:
	yych = *++cursor;
yy128:
	switch (yych) {
		case '\t':
		case ' ': goto yy127;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy132;
		default: goto yy19;
	}
yy129:
	yych = *++cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy133;
		default: goto yy19;
	}
yy130:
	yych = *++cursor;
	switch (yych) {
		case 'r': goto yy134;
		default: goto yy19;
	}
yy131:
	++cursor;
#line 69 "implicit.re"
	{   return "int#na"; }
#line 1111 "<stdout>"
yy132:
	yych = *++cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy135;
		default: goto yy19;
	}
yy133:
	yych = *++cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy136;
		default: goto yy19;
	}
yy134:
	yych = *++cursor;
	if (yych <= 0x00) goto yy137;
	goto yy19;
yy135:
	yych = *++cursor;
	switch (yych) {
		case ':': goto yy138;
		default: goto yy19;
	}
yy136:
	yych = *++cursor;
	switch (yych) {
		case ':': goto yy139;
		default: goto yy19;
	}
yy137:
	++cursor;
#line 95 "implicit.re"
	{   return "str#na"; }
#line 1162 "<stdout>"
yy138:
	yych = *++cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy140;
		default: goto yy19;
	}
yy139:
	yych = *++cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy141;
		default: goto yy19;
	}
yy140:
	yych = *++cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy142;
		default: goto yy19;
	}
yy141:
	yych = *++cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy143;
		default: goto yy19;
	}
yy142:
	yych = *++cursor;
	switch (yych) {
		case ':': goto yy144;
		default: goto yy19;
	}
yy143:
	yych = *++cursor;
	switch (yych) {
		case ':': goto yy145;
		default: goto yy19;
	}
yy144:
	yych = *++cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy146;
		default: goto yy19;
	}
yy145:
	yych = *++cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy147;
		default: goto yy19;
	}
yy146:
	yych = *++cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy148;
		default: goto yy19;
	}
yy147:
	yych = *++cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy149;
		default: goto yy19;
	}
yy148:
	yych = *++cursor;
	switch (yych) {
		case '.': goto yy151;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy19;
		default: goto yy152;
	}
yy149:
	yych = *++cursor;
	switch (yych) {
		case '.': goto yy154;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy19;
		default: goto yy155;
	}
yy150:
	yych = *++cursor;
	switch (yych) {
		case '\t':
		case ' ': goto yy150;
		case '+':
		case '-': goto yy157;
		case 'Z': goto yy158;
		default: goto yy19;
	}
yy151:
	yych = *++cursor;
yy152:
	switch (yych) {
		case '\t':
		case ' ': goto yy150;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy151;
		default: goto yy19;
	}
yy153:
	yych = *++cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy159;
		default: goto yy19;
	}
yy154:
	yych = *++cursor;
yy155:
	switch (yych) {
		case '+':
		case '-': goto yy153;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy154;
		case 'Z': goto yy156;
		default: goto yy19;
	}
yy156:
	yych = *++cursor;
	if (yych <= 0x00) goto yy160;
	goto yy19;
yy157:
	yych = *++cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy161;
		default: goto yy19;
	}
yy158:
	yych = *++cursor;
	if (yych <= 0x00) goto yy162;
	goto yy19;
yy159:
	yych = *++cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy163;
		default: goto yy19;
	}
yy160:
	++cursor;
#line 89 "implicit.re"
	{   return "timestamp#iso8601"; }
#line 1431 "<stdout>"
yy161:
	yych = *++cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy164;
		default: goto yy19;
	}
yy162:
	++cursor;
#line 91 "implicit.re"
	{   return "timestamp#spaced"; }
#line 1451 "<stdout>"
yy163:
	yych = *++cursor;
	switch (yych) {
		case 0x00: goto yy160;
		case ':': goto yy165;
		default: goto yy19;
	}
yy164:
	yych = *++cursor;
	switch (yych) {
		case 0x00: goto yy162;
		case ':': goto yy166;
		default: goto yy19;
	}
yy165:
	yych = *++cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy167;
		default: goto yy19;
	}
yy166:
	yych = *++cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy168;
		default: goto yy19;
	}
yy167:
	yych = *++cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy156;
		default: goto yy19;
	}
yy168:
	yych = *++cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy158;
		default: goto yy19;
	}
}
#line 103 "implicit.re"


}
